//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NECTestPattern.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NECTESTPATTERN_DIALOG       102
#define IDS_ERR_PATTERNFILE             102
#define IDS_ERR_SELECTMONITOR           103
#define IDS_SETTESTPATTERN_TI           104
#define IDS_WAR_SELECTMONITOR_ONE       105
#define IDS_WAR_SELECTMONITOR_ALL       106
#define IDS_MSG_EXIT                    107
#define IDS_MSG_SETEND                  108
#define IDS_MSG_SETTING                 109
#define IDS_MSG_SETTING_TI              110
#define IDS_MSG_TESTTING1               111
#define IDS_MSG_TESTTING2               112
#define IDS_MSG_TESTTING3               113
#define IDS_MSG_TESTTING4               114
#define IDS_MSG_TESTTING5               115
#define IDS_MSG_TESTTING6               116
#define IDS_MSG_TESTTING7               117
#define IDS_MSG_TI_TESTING1             118
#define IDS_MSG_TI_TESTING2             119
#define IDS_MSG_TI_TESTING3             120
#define IDS_MSG_TI_TESTING4             121
#define IDS_MSG_TI_TESTING5             122
#define IDS_MSG_TI_TESTING6             123
#define IDS_MSG_TI_TESTING7             124
#define IDS_MSG_TI_TESTING_TIME         125
#define IDR_MAINFRAME                   128
#define IDD_TEST_PATTERN                129
#define IDB_BITMAP_PREVIEW              130
#define IDD_SETTESTPATTERN              130
#define IDI_ICON_PATTERN7               131
#define IDB_BITMAP_PATTERN7             131
#define IDD_SETTING_MSG_DIALOG          133
#define IDD_SETTING_REMIND_DIALOG       134
#define IDI_ICON_PATTERN_CALC1          135
#define IDD_REMIND_DIALOG               135
#define IDR_MAINFRAME1                  136
#define IDB_BITMAP_REMIND1              136
#define IDD_CALC_DIALOG                 136
#define IDI_ICON_PATTERN_CALC2          137
#define IDB_BITMAP_REMIND2              137
#define IDR_MENU_MAIN                   137
#define IDD_MESSAGE_DIALOG              137
#define IDI_ICON_PATTERN_CALC3          138
#define IDD_TESTTINGMESSAGE_DIALOG      138
#define IDD_SOFT_OPTION                 139
#define IDI_ICONINFORMATION             145
#define IDS_WAR_CALC1                   201
#define IDS_WAR_CALC2                   202
#define IDS_WAR_CALC3                   203
#define IDC_STATIC_PATTERN              1000
#define IDC_LIST_DISPLAY                1001
#define IDC_RADIO_ALL                   1003
#define IDC_RADIO_ONE                   1004
#define IDC_EDIT_FILENAME               1005
#define IDC_BUTTON_FILE                 1006
#define IDC_STATIC_PREVIEW              1007
#define IDC_BUTTON_FILEDISPLAY          1008
#define IDC_EXITDLG                     1010
#define IDC_RADIO_FirstCen              1011
#define IDC_RADIO_FirstExt              1012
#define IDC_RADIO_FirstEnu              1013
#define IDC_BUTTON_PATTERN1             1021
#define IDC_STATIC_BMPBK1               1021
#define IDC_STATIC_BMPBK2               1022
#define IDC_STATIC_Enu                  1022
#define IDC_STATIC_BMPBK3               1023
#define IDC_RADIO_Enu_left              1023
#define IDC_STATIC_BMPBK4               1024
#define IDC_RADIO_Enu_cen               1024
#define IDC_RADIO_Enu_right             1025
#define IDC_RADIO_Enu_up                1026
#define IDC_RADIO_Enu_ccen              1027
#define IDC_RADIO_Enu_down              1028
#define IDC_STATIC_Ext                  1029
#define IDC_RADIO_Ext_Width             1030
#define IDC_RADIO_Ext_Height            1031
#define IDC_RADIO_Ext_Pack              1032
#define IDC_STATIC_Color                1033
#define IDC_RADIO_Color_leftup          1034
#define IDC_RADIO_Color_leftdown        1035
#define IDC_RADIO_Color_cen             1036
#define IDC_RADIO_Color_rightup         1037
#define IDC_RADIO_Color_rightdown       1038
#define IDC_BUTTON_PATTERN2             1039
#define IDC_DONOT                       1040
#define IDC_CHECK_ALL                   1040
#define IDC_BUTTON_PATTERN3             1041
#define IDC_STATIC_TEXT                 1042
#define IDC_BUTTON_PATTERN_CALC1        1042
#define IDC_BUTTON_PATTERN_CALC2        1043
#define IDC_BUTTON_PATTERN_CALC3        1044
#define IDC_RADIO_COLOR_SELECT          1045
#define IDC_RADIO_COLOR_FILE            1046
#define IDC_STATIC_COLOR_FILE           1047
#define IDC_STATIC_COLOR_SELECT         1048
#define IDC_STATIC_SELECTED_COLOR       1049
#define IDC_BUTTON_SELECT_COLOR         1050
#define IDC_STATIC_REMIND1              1051
#define IDC_STATIC_REMIND2              1052
#define IDC_CHECK_SHOW                  1056
#define IDC_RADIO1                      1060
#define IDC_RADIO2                      1061
#define IDC_RADIO3                      1062
#define IDC_STATIC_STRING               1067
#define IDC_STATIC_ICON                 1068
#define IDC_EDIT_TIME                   1069
#define IDC_BUTTON_NEXT                 1070
#define IDC_BUTTON_BACK                 1071
#define IDC_RADIO_M                     1072
#define IDC_RADIO_A                     1073
#define IDC_STATIC_TIME                 1074
#define IDC_CHECK1                      1075
#define IDC_CHECK2                      1076
#define IDC_CHECK3                      1077
#define IDC_CHECK4                      1078
#define IDC_BACK                        1200
#define ID_MENUITEM_OPTION              32771
#define ID_MENUITEM_EXIT                32772
#define ID_MENUITEM_LANGUAGE_EN         32773
#define ID_MENUITEM_LANGUAGE_JP         32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
